url: https://reeswrites.com
baseurl: ""
title: "Rees Writes"
author: "Rees D."
description: "Where I blog about my various interests and things that I am working on."
permalink: /posts/:title/
timezone: "America/New_York"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
feed:
  disable_in_development: true
  posts_limit: 25